Update puppet-apply

diff --git a/puppet-apply b/puppet-apply
--- a/puppet-apply
+++ b/puppet-apply
@@ -3,7 +3,14 @@
 set -e
 
 if [ $(dpkg-query -W -f='${Status}' curl 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
-  echo "Please install curl"
+  echo "Installing curl...."
+  sudo apt-get install curl
+  exit 0
+fi
+
+if [ $(dpkg-query -W -f='${Status}' puppet 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
+  echo "Installing puppet"
+  sudo apt-get install puppet
   exit 0
 fi
 
@@ -12,7 +19,7 @@ local_sha512=$(sha512sum "/etc/puppe/site.pp" | awk '{print $1}')
 online_facter_sha512=$(curl -s https://raw.githubusercontent.com/cedricbrx/puppet-debian/master/facter_brandenbourger.sh | sha512sum | awk '{print $1}')
 local_facter_sha512=$(sha512sum "/var/cache/puppet/facts.d/facter_brandenbourger.sh" | awk '{print $1}')
 
-if [[ "$online_sha512" != "$local_sha512" ]] || [[ "$online_facter_sha512" != "$local_facter_sha512" ]] ; then
+if [[ "$online_sha512" != "$local_sha512" ]] || [[ "$online_facter_sha512" != "$local_facter_sha512" ]] || [[ `date '+%A'` == "Sunday" ]] ; then
   cd /etc/puppet
   wget -N -q https://raw.githubusercontent.com/cedricbrx/puppet-debian/master/site.pp
   cd /var/cache/puppet/facts.d/
@@ -23,26 +30,12 @@ if [[ "$online_sha512" != "$local_sha512" ]] || [[ "$online_facter_sha512" != "$
   	/usr/bin/logger -i "Puppet has no internet connection, exiting" -t "puppet-apply"
 	exit 1
   fi
- puppet apply /etc/puppet/site.pp
-	if [ $? -eq 0 ]; then
-          /usr/bin/logger -i "Puppet has run successfully" -t "puppet-apply"
-          exit 0
-	else
-          /usr/bin/logger -i "Puppet has run into an error, please run Puppet manually" -t "puppet-apply"
-          exit 1
-        fi
-else
-    if [ `date '+%A'` != "Sunday" ]; then
-       	/usr/bin/logger -i "Nothing to do" -t "puppet-apply"
-    	exit 0
-    else
-        puppet apply /etc/puppet/site.pp
-	if [ $? -eq 0 ]; then
-          /usr/bin/logger -i "Puppet has run successfully on Sunday" -t "puppet-apply"
-          exit 0
-	else
-          /usr/bin/logger -i "Puppet has run into an error on Sunday, please run Puppet manually" -t "puppet-apply"
-          exit 1
-        fi
-    fi
+  puppet apply /etc/puppet/site.pp
+  if [ $? -eq 0 ]; then
+      /usr/bin/logger -i "Puppet has run successfully" -t "puppet-apply"
+      exit 0
+  else
+      /usr/bin/logger -i "Puppet has run into an error, please run Puppet manually" -t "puppet-apply"
+      exit 1
+  fi
 fi
